Simply multichain running
subquery/subql pull request #1746
Opened 2023-05-23 07:22 UTC by DeveloperInProgress

# Description
Allow multichain projects to be built with single codegen and build command. Add new child manifests with cli. 

Fixes #1636 

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Checklist

- [ ] I have tested locally
- [ ] I have performed a self review of my changes
- [ ] Updated any relevant documentation
- [ ] Linked to any relevant issues
- [ ] I have added tests relevant to my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] My code is up to date with the base branch
- [ ] I have updated relevant changelogs. [We suggest using chan](https://github.com/geut/chan/tree/main/packages/chan)

2023-05-24 02:06 UTC, jiqiang90 commented on packages/cli/src/commands/add-chain.ts
> +    multichain: Flags.string({char: 'm', description: 'specify multichain manifest file path'}),
little confused here with `multichain manifest` and `new chain manifest`

2023-05-24 20:59 UTC, stwiname reviewed
This is a good opportunity to have tests. Everything here can be easily testable.

There can also be many improvements to types. We should not use `any` except when we cannot find any alternative.

Some of these changes don't look backwards compatible. The user should still be able to use the CLI as is now without having to have a multichain manifest

2023-05-24 20:59 UTC, stwiname commented on packages/cli/src/controller/add-chain-controller.ts
> +    multichainManifest = yaml.load(fs.readFileSync(multichainManifestPath, 'utf8')) as ProjectManifestParentV1_0_0;
I think we had a new way of loading and writing yaml that retained the comments in the file

2023-05-24 20:59 UTC, stwiname commented on packages/cli/src/controller/add-chain-controller.ts
> +  const subqlNodeServices = Object.keys(dockerCompose.services).filter((key) =>
You can use `Object.values` and find if you only need the one.

2023-05-24 20:59 UTC, stwiname commented on packages/cli/src/controller/add-chain-controller.ts
> +function getSubqlNodeService(dockerCompose: DockerComposeType): any {
Return type please

2023-05-24 20:59 UTC, stwiname commented on packages/cli/src/commands/publish.ts
> +    for (const manifest of project.manifests) {
If its multichain, we should create a directory on ipfs

2023-06-02 01:18 UTC, stwiname requested changes
I did some testing and all the commands i tried failed

## Issues from testing:
### Non multichain projects:
* `./bin/run codegen -f ~/Projects/subql-dictionary/moonbeam-evm` and ``./bin/run codegen -f ~/Projects/subql-dictionary/moonbeam-evm/project.yaml` both fail with ` Error: Could not find project manifest under dir .`
* `./bin/run publish -f ~/Projects/subql-dictionary/moonbeam-evm/project.yaml` and `./bin/run publish -f ~/Projects/subql-dictionary/moonbeam-evm` fails with `Error: unknown location: project.yaml`
### Multichain project:
* codegen is the same as above
* Publish cannot find project file: `Error: unknown location: moonbeam_project.yaml`
* `./bin/run multi-chain:add -f ~/Projects/api-nft-erc721/subquery-multichain.yaml` doesnt modify docker compose in the right place `Error: Docker Compose file does not exist at the specified location: /Users/scotttwiname/Projects/subql-main/packages/cli/docker-compose.yml`

2023-06-05 21:57 UTC, stwiname requested changes
After more testing I'm still facing issues:

* A directory with no `project.yaml` exits without any error message for `codegen` and `publish`
* A directory with a `subquery-multichain.yaml` file exits without doing anything for `codegen` and `publish`
* Publishing a multichain project with one chain only logs one CID and its the CID of the one chain. It doesn't say which chain it is for or if its the multi-chain manifest
* Adding a chain to multichain doesn't log anything. I don't know if it works without viewing the files
* Adding the same chain to multichain adds it again to the manifest file. It should ignore it if its already there.
* Docker compose doesn't include the `multi-chain` flag

2023-06-05 21:57 UTC, stwiname commented on packages/cli/src/commands/multi-chain/add.ts
> +    multichain: Flags.string({char: 'm', description: 'specify multichain manifest file path'}),
I think `-f` should be the multichain manifest file.

2023-06-05 21:57 UTC, stwiname commented on packages/cli/src/commands/multi-chain/add.ts
> +export default class MultiChainAdd extends Command {
Can we make this interactive as well please

2023-06-06 03:34 UTC, DeveloperInProgress commented
> * A directory with a `subquery-multichain.yaml` file exits without doing anything for `codegen` and `publish`

right now the default name for a multichain manifest file is `multichain-manifest.yaml`

2023-06-06 03:36 UTC, stwiname commented
> > * A directory with a `subquery-multichain.yaml` file exits without doing anything for `codegen` and `publish`
> 
> right now the default name for a multichain manifest file is `multichain-manifest.yaml`

Can it be `subquery-multichain` like in the issue please

2023-06-07 04:29 UTC, stwiname requested changes
It seems codegen is being run for the same files multiple times:
```
➜ ./bin/run codegen -f  ~/Projects/api-nft-erc721
===============================
---------Subql Codegen---------
===============================
Clearing generated files
Cleared generated directory: /Users/scotttwiname/Projects/api-nft-erc721/src/types
* Schema Nft generated !
* Schema Collection generated !
* Schema Transfers generated !
* Schema Address generated !
* Schema Network generated !
* Models index generated !
* Abi Interface Erc721 generated
* Abi Interface Erc1155 generated
* Types index generated !
* Abi Interface Erc721 generated
* Abi Interface Erc1155 generated
* Types index generated !
* Abi Interface Erc721 generated
* Abi Interface Erc1155 generated
* Types index generated !
```

Adding a new chain with chain id:
```
./bin/run multi-chain:add -f ~/Projects/api-nft-erc721/subquery-multichain.yaml  --chainId=592
Enter the path to the new chain manifest: astar.yaml
    TypeError: The "path" argument must be of type string or an instance of Buffer or URL. Received an instance of YAMLSeq
    Code: ERR_INVALID_ARG_TYPE
```
If the current directory is a project `-f` should be unnecessary

Please do more testing. I stopped once I found enough issues

2023-06-07 04:29 UTC, stwiname commented on packages/cli/src/commands/multi-chain/add.ts
> +    schema: Flags.string({char: 's', description: 'specify schema path for the new chain manifest'}),
How come a schema needs to be provided? They should all have the same schema

2023-06-12 23:06 UTC, stwiname reviewed
I ended up wiith a docker compose that had this section:
```
    command:
      - -f=app/project-astar.yaml
      - --disable-historical
      - -f=/app/project-moonbeam.yaml
      - --db-schema=app
      - --batch-size=30
```

The logging for adding a chain seems excessive:
```
Validating chain manifest...
Chain manifest: project-astar.yaml
Chain manifest schema path: /Users/scotttwiname/Projects/api-nft-erc721/schema.graphql
Validating project: project-moonbeam.yaml
Project schema path: /Users/scotttwiname/Projects/api-nft-erc721/schema.graphql
Adding chain manifest path: project-astar.yaml
Updating Docker Compose for chain manifest: /Users/scotttwiname/Projects/api-nft-erc721/project-astar.yaml
Service name: subquery-node-project-astar
Docker Compose file path: /Users/scotttwiname/Projects/api-nft-erc721/docker-compose.yml
Created new service configuration: subquery-node-project-astar
Docker Compose file updated successfully at: /Users/scotttwiname/Projects/api-nft-erc721/docker-compose.yml
```

How can I see the directory IPFS CID when uploading a multichain project?

Theres a couple of types improvements to be made, see the github annotations

2023-06-13 02:30 UTC, DeveloperInProgress commented on packages/cli/src/controller/add-chain-controller.ts
> +function generateChainManifest(chainId: string): string {
It was expected in the issue. but, currently the implementation is unclear

2023-06-15 21:55 UTC, stwiname reviewed
- Publishing doesn't upload `subquery-multichain.yaml` in the directory
- There's still a few linter warnings (see annotations)

2023-06-15 21:55 UTC, stwiname commented on packages/cli/src/commands/publish.ts
>      }
I don't think we need this directory stuff. Its not relevant and just makes the logging confusing

2023-06-15 21:55 UTC, stwiname commented on packages/cli/src/controller/add-chain-controller.ts
> +function generateChainManifest(chainId: string): string {
Lets remove this code as discussed

2023-06-15 21:55 UTC, stwiname commented on packages/cli/src/controller/codegen-controller.ts
> +  const propsWithoutDuplicates = props.filter((prop, index) => {
https://lodash.com/docs/4.17.15#uniqBy

2023-06-18 23:38 UTC, stwiname reviewed
When uploading subquery-multichain we need to replace the file paths with ipfs links to the chain files

2023-06-19 03:40 UTC, stwiname approved these changes

2023-06-19 03:40 UTC, merged