add support for null ordering in 'order by' query (#2387)
subquery/subql pull request #2526
Opened 2024-08-09 12:46 UTC by abhishek818

# Description
adds support for null ordering in 'order by' query

Fixes #2387 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [ ] I have tested locally
- [X] I have performed a self review of my changes
- [ ] Updated any relevant documentation
- [X] Linked to any relevant issues
- [ ] I have added tests relevant to my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [X] My code is up to date with the base branch
- [ ] I have updated relevant changelogs. [We suggest using chan](https://github.com/geut/chan/tree/main/packages/chan)

2024-08-09 12:49 UTC, abhishek818 commented
@stwiname @jiqiang90 hey are the test suites broken (some pass, others fail) ?
Was trying to add a test case in packages\query\src\graphql\graphql.test.ts file. Can you help with running the tests (any specific set of commands etc.)

2024-08-09 13:07 UTC, abhishek818 commented
anyways up for a review..

2024-08-11 22:07 UTC, stwiname commented
> @stwiname @jiqiang90 hey are the test suites broken (some pass, others fail) ? Was trying to add a test case in **packages\query\src\graphql\graphql.test.ts** file. Can you help with running the tests (any specific set of commands etc.)

@abhishek818 because its an integration test it needs a DB to connect to. You can either run postgres yourself or `yarn test:docker` but you would probably want to change it to just run that test.

These changes look good but tests are still needed,

2024-08-12 16:10 UTC, abhishek818 commented
Added the tests, Up for review..

`test-1  | PASS packages/query/src/graphql/graphql.test.ts (863 MB heap size)`

2024-08-13 22:00 UTC, stwiname approved these changes

2024-08-13 22:35 UTC, stwiname requested changes
There is a failing test `GraphqlHistorical › to filter historical items when ordering`, this is a change in behaviour as if the nulls order is not specified then it should be default. 

As the [Postgres docs](https://www.postgresql.org/docs/current/queries-order.html#QUERIES-ORDER) say `ASC` and `DESC` change the default null behaviour. This should be retained if null order isn't specified.

2024-08-15 08:52 UTC, abhishek818 commented
> There is a failing test `GraphqlHistorical › to filter historical items when ordering`, this is a change in behaviour as if the nulls order is not specified then it should be default.
> 
> As the [Postgres docs](https://www.postgresql.org/docs/current/queries-order.html#QUERIES-ORDER) say `ASC` and `DESC` change the default null behaviour. This should be retained if null order isn't specified.

Thanks for pointing this out. Have fixed this.
Up for a review now..

2024-08-18 21:10 UTC, stwiname approved these changes

2024-08-18 21:10 UTC, merged