Injecting logging module
subquery/subql pull request #259
Opened 2021-04-07 10:41 UTC by jiqiang90

Closes #248

2021-04-07 20:23 UTC, zhex approved these changes

2021-04-07 21:44 UTC, ianhe8x requested changes

2021-04-07 21:44 UTC, ianhe8x commented on packages/common/src/logger/logger.ts
> +  constructor({level, nestedKey, outputFormat}: LoggerOption) {
It is intended using alias logLevel, to avoid variable naming conflict. e.g at line 62

2021-04-07 21:45 UTC, ianhe8x commented
fix tests

2021-04-08 02:44 UTC, ianhe8x approved these changes

2021-04-08 02:44 UTC, merged