WIP: Add authToken to ipfs-http header
subquery/subql pull request #778
Opened 2022-01-27 03:01 UTC by wqsz7xn

- Adds a yaml file for secrets and a flag for a secret authToken
- This yaml doesn't have a spec because it's likely to remain small and I think we would want breaking changes for changes to this yaml. Not using a normal file so that we have the possibility of expanding if we need to later
- **WIP** because I don't know how this is going to work in practice for either hosted or decentralised

2022-02-04 07:25 UTC, stwiname reviewed
I think users might think the `secret` flag relates to the `ipfs` endpoint they specify when it would actually get sent to our cluster. It could be considered deceptive.

2022-02-04 07:25 UTC, stwiname commented on packages/cli/src/controller/publish-controller.ts
> +  const results = await Promise.allSettled([clientPromise, clusterPromise]);
This might be better suited https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/any

2022-02-07 22:33 UTC, ianhe8x commented on packages/cli/src/commands/publish.ts
> +        authToken = (yaml.load(readFileSync(path.resolve(directory, 'auth.yaml'), 'utf8')) as AuthorizationSpec).secret;
I don't think this is a project level thing. better store it in user's HOME

2022-02-08 02:59 UTC, ianhe8x commented on packages/cli/src/commands/publish.ts
> +    'access-token': flags.string({description: 'Secret authorization token', required: false}),
For env variable & flag, I think just one of them should be enough.

2022-02-08 02:59 UTC, ianhe8x commented on packages/cli/src/commands/publish.ts
> +const ACCESS_TOKEN_PATH = path.resolve(process.env.HOME, '.SUBQL_ACCESS_TOKEN');
suggest to put it under `.subql` in case more files added

2022-02-09 07:03 UTC, ianhe8x requested changes

2022-02-09 07:03 UTC, ianhe8x commented on packages/cli/src/controller/publish-controller.ts
> +  return result.cid['/'];
- 
```suggestion
  return result.cid?.['/'];
```

2022-02-09 08:42 UTC, ianhe8x approved these changes

2022-02-09 08:42 UTC, merged