move polkadot dependencies to util package
subquery/subql pull request #958
Opened 2022-05-03 01:18 UTC by jiqiang90

so node and node-terra can share it

2022-05-03 04:40 UTC, stwiname approved these changes

2022-05-03 04:43 UTC, stwiname requested changes
It appears there are imports in node terra for `@polkadot/util-crypto`

2022-05-03 04:43 UTC, stwiname commented
We can get Naveen to do this

2022-05-05 02:16 UTC, ianhe8x approved these changes

2022-08-01 01:04 UTC, stwiname commented
Closing this for now. We are currently using these functions for MMR/Poi hashes as well as unique db keys

2022-08-01 01:04 UTC, closed without merging